### ISSUE TITLE
Dimension name is not displayed on the server

### ISSUE THREAD

**Issue by GedeonGrays** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#57] opened 2024-04-20 16:57 UTC
Hello o/

**Minecraft Version:** 1.7.10
**Chunk-Pregenerator Version:** 4.4.5
**Server Version:** any (pure Forge server too)

**Video report:** 

https://github.com/TinyModularThings/Chunk-Pregenerator-Issue-Tracker/assets/32182901/1ca85409-c466-45ad-8baf-6d2844b8745b

Dimension names are not defined on any server, which is a bit inconvenient. At the same time, the target dimension selection works properly. 
In singleplayer, everything displays normally.

**Comment by Speiger** [comment] 2024-04-20 17:23
@GedeonGrays interesting. That means that information isn't send to the client for some reason...

Hmmm not sure why.
But yeah i will address that with the next patch.
Sadly that will take a bit due to me being busy for the next few months and only fixing "Emergency only issues"
(Emergency only issues => mod is not usable due to constant crashloop or basically breaking 100% of the mod, whic this one isn't the case right now)

**Comment by GedeonGrays** [comment] 2024-04-20 17:35
> @GedeonGrays interesting. That means that information isn't send to the client for some reason...
> 
> Hmmm not sure why. But yeah i will address that with the next patch. Sadly that will take a bit due to me being busy for the next few months and only fixing "Emergency only issues" (Emergency only issues => mod is not usable due to constant crashloop or basically breaking 100% of the mod, whic this one isn't the case right now)

Of course, I understand and will wait as long as you need. After all, the mod can still be used ¯\_(ツ)_/¯

**Comment by Speiger** [comment] 2024-06-17 15:18
@GedeonGrays sorry for the delay.
The issue is now fixed and will be released soon.
When this issue is closed the update will have been submitted to curseforge

**Closed as completed** 2024-06-22 15:33 UTC
Labels: Done for next patch
