### ISSUE TITLE
[1.7.10 Crucible] CodeChickenLib server crash

### ISSUE THREAD

**Issue by iocmet** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#34] opened 2023-06-27 22:18 UTC
`[01:17:33] [Server thread/WARN]: java.lang.NullPointerException
[01:17:33] [Server thread/WARN]: 	at codechicken.lib.world.WorldExtension.saveChunkData(WorldExtension.java:62)
[01:17:33] [Server thread/WARN]: 	at codechicken.lib.world.WorldExtensionManager$WorldExtensionEventHandler.onChunkDataSave(WorldExtensionManager.java:42)
[01:17:33] [Server thread/WARN]: 	at cpw.mods.fml.common.eventhandler.ASMEventHandler_661_WorldExtensionEventHandler_onChunkDataSave_Save.invoke(.dynamic)
[01:17:33] [Server thread/WARN]: 	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[01:17:33] [Server thread/WARN]: 	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:168)
[01:17:33] [Server thread/WARN]: 	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:221)
[01:17:33] [Server thread/WARN]: 	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:417)
[01:17:33] [Server thread/WARN]: 	at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:501)
[01:17:33] [Server thread/WARN]: 	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1094)
[01:17:33] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftWorld.save(CraftWorld.java:806)
[01:17:33] [Server thread/WARN]: 	at autosaveworld.features.save.AutoSaveThread.saveWorldNormal(AutoSaveThread.java:159)
[01:17:33] [Server thread/WARN]: 	at autosaveworld.features.save.AutoSaveThread.saveWorld(AutoSaveThread.java:150)
[01:17:33] [Server thread/WARN]: 	at autosaveworld.features.save.AutoSaveThread.performSaveNow(AutoSaveThread.java:81)
[01:17:33] [Server thread/WARN]: 	at autosaveworld.core.AutoSaveWorld.onDisable(AutoSaveWorld.java:157)
[01:17:33] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:318)
[01:17:33] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:386)
[01:17:33] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:428)
[01:17:33] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:421)
[01:17:33] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.disablePlugins(CraftServer.java:351)
[01:17:33] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:570)
[01:17:33] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:754)
[01:17:33] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:750)`

**Comment by Speiger** [comment] 2023-06-28 06:21
Look under 1.12 or older known issues.
There is a fix for this specific crash.

Chickenbones mod is the cause

**Closed** 2023-06-28 06:21 UTC
