### ISSUE TITLE
Crashes when joining

### ISSUE THREAD

**Issue by coolboy2002** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#56] opened 2024-04-02 17:33 UTC
Sorry for opening another issue, but apparently what happens when it hangs and I join the server is that the server crashes sometimes. Not sure if this has to do with Chunk Cascading again. Do you maybe have discord so I can DM you instead of opening an issue on here? I think it's also pretty annoying for you :D

**Comment by Speiger** [comment] 2024-04-02 17:34
@coolboy2002 clearly the server isn't crashing, because there isn't a crashlog.

**Comment by coolboy2002** [comment] 2024-04-02 17:35
It does crash, I have had it 2 times when it hanged on chunk loading. I tried joining when it did and then it crashed the server.
If I don't join it seems to slowly but really slowly continue on but when I join the server it will just take a little moment and crash.

**Comment by Speiger** [comment] 2024-04-02 17:53
@coolboy2002 you are not getting the hint i Literally gave.
No Log provided => It doesn't happen.
Otherwise I can't help you and only can close the issue and view it as spam

So again: Clearly it doesn't crash since I can't see a log.

**Comment by coolboy2002** [comment] 2024-04-02 19:46
Okay, you can calm down, sorry. I will get a log once I join it again.

**Comment by coolboy2002** [comment] 2024-04-03 07:25
<details>
<summary>Crashlog</summary>
<p>

[01:01:55] [Server thread/WARN] [universalmodcore]: Calculating Immersive Railroading Physics Iteration took 32ms (0, 0, 0)
[01:29:48] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: 
[01:29:48] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [TaskName: Overworld1][Shape: Square]
[01:29:48] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Dim=Overworld] [Task Type: Fast Check Gen]
[01:29:48] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Task: Current/Total: 207,804/4,428,287]
[01:29:48] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Speed: 2.5 Chunks/t]
[01:29:48] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Loaded (Chunks | Region Files): 272 | 100]
[01:29:48] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Working Area: From[X=5120, Z=11776], To[X=5632, Z=12288]]
[01:29:48] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Time Left: 23:26:53, Running: 32:01:47]
[01:29:48] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Ram Usage: 4381 MB / 6372 MB][Ticks: 372]
[01:29:48] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Listen][Mute][Pause][Resume][Stop][Continue][Remove]
[01:48:15] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: 
[01:48:15] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [TaskName: Overworld1][Shape: Square]
[01:48:15] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Dim=Overworld] [Task Type: Fast Check Gen]
[01:48:15] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Task: Current/Total: 207,805/4,428,287]
[01:48:15] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Speed: 2.5 Chunks/t]
[01:48:15] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Loaded (Chunks | Region Files): 272 | 100]
[01:48:15] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Working Area: From[X=5120, Z=11776], To[X=5632, Z=12288]]
[01:48:15] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Time Left: 23:26:56, Running: 32:20:14]
[01:48:15] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Ram Usage: 4085 MB / 6372 MB][Ticks: 511]
[01:48:15] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Listen][Mute][Pause][Resume][Stop][Continue][Remove]
[02:55:42] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: 
[02:55:43] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [TaskName: Overworld1][Shape: Square]
[02:55:43] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Dim=Overworld] [Task Type: Fast Check Gen]
[02:55:43] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Task: Current/Total: 207,806/4,428,287]
[02:55:43] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Speed: 2.5 Chunks/t]
[02:55:43] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Loaded (Chunks | Region Files): 272 | 100]
[02:55:43] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Working Area: From[X=5120, Z=11776], To[X=5632, Z=12288]]
[02:55:43] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Time Left: 23:26:59, Running: 33:27:42]
[02:55:43] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Ram Usage: 4605 MB / 6372 MB][Ticks: 206]
[02:55:43] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Listen][Mute][Pause][Resume][Stop][Continue][Remove]
[03:21:42] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: 
[03:21:42] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [TaskName: Overworld1][Shape: Square]
[03:21:42] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Dim=Overworld] [Task Type: Fast Check Gen]
[03:21:42] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Task: Current/Total: 207,807/4,428,287]
[03:21:42] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Speed: 2.5 Chunks/t]
[03:21:42] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Loaded (Chunks | Region Files): 272 | 100]
[03:21:42] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Working Area: From[X=5120, Z=11776], To[X=5632, Z=12288]]
[03:21:42] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Time Left: 23:27:01, Running: 33:53:42]
[03:21:42] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Ram Usage: 4553 MB / 6372 MB][Ticks: 4]
[03:21:43] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Listen][Mute][Pause][Resume][Stop][Continue][Remove]
[03:39:34] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: 
[03:39:34] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [TaskName: Overworld1][Shape: Square]
[03:39:34] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Dim=Overworld] [Task Type: Fast Check Gen]
[03:39:34] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Task: Current/Total: 207,808/4,428,287]
[03:39:34] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Speed: 2.5 Chunks/t]
[03:39:34] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Loaded (Chunks | Region Files): 272 | 100]
[03:39:34] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Working Area: From[X=5120, Z=11776], To[X=5632, Z=12288]]
[03:39:34] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Time Left: 23:27:04, Running: 34:11:34]
[03:39:34] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Ram Usage: 3895 MB / 6372 MB][Ticks: 363]
[03:39:34] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Listen][Mute][Pause][Resume][Stop][Continue][Remove]
[03:51:08] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: 
[03:51:08] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [TaskName: Overworld1][Shape: Square]
[03:51:08] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Dim=Overworld] [Task Type: Fast Check Gen]
[03:51:09] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Task: Current/Total: 207,809/4,428,287]
[03:51:09] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Speed: 2.5 Chunks/t]
[03:51:09] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Loaded (Chunks | Region Files): 272 | 100]
[03:51:09] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Working Area: From[X=5120, Z=11776], To[X=5632, Z=12288]]
[03:51:09] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Time Left: 23:27:08, Running: 34:23:08]
[03:51:09] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Ram Usage: 3729 MB / 6372 MB][Ticks: 309]
[03:51:09] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Listen][Mute][Pause][Resume][Stop][Continue][Remove]
[03:51:46] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: 
[03:51:46] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [TaskName: Overworld1][Shape: Square]
[03:51:46] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Dim=Overworld] [Task Type: Fast Check Gen]
[03:51:46] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Task: Current/Total: 207,810/4,428,287]
[03:51:46] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Speed: 2.5 Chunks/t]
[03:51:46] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Loaded (Chunks | Region Files): 272 | 100]
[03:51:46] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Working Area: From[X=5120, Z=11776], To[X=5632, Z=12288]]
[03:51:46] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Time Left: 23:27:11, Running: 34:23:46]
[03:51:46] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Ram Usage: 4113 MB / 6372 MB][Ticks: 16]
[03:51:46] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Listen][Mute][Pause][Resume][Stop][Continue][Remove]
[04:17:34] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: 
[04:17:34] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [TaskName: Overworld1][Shape: Square]
[04:17:34] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Dim=Overworld] [Task Type: Fast Check Gen]
[04:17:34] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Task: Current/Total: 207,811/4,428,287]
[04:17:34] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Speed: 2.5 Chunks/t]
[04:17:34] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Loaded (Chunks | Region Files): 272 | 100]
[04:17:34] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Working Area: From[X=5120, Z=11776], To[X=5632, Z=12288]]
[04:17:34] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Time Left: 23:27:14, Running: 34:49:33]
[04:17:34] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Ram Usage: 3924 MB / 6372 MB][Ticks: 131]
[04:17:34] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Listen][Mute][Pause][Resume][Stop][Continue][Remove]
[04:34:50] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: 
[04:34:50] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [TaskName: Overworld1][Shape: Square]
[04:34:50] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Dim=Overworld] [Task Type: Fast Check Gen]
[04:34:50] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Task: Current/Total: 207,812/4,428,287]
[04:34:50] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Speed: 2.5 Chunks/t]
[04:34:50] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Loaded (Chunks | Region Files): 272 | 100]
[04:34:50] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Working Area: From[X=5120, Z=11776], To[X=5632, Z=12288]]
[04:34:50] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Time Left: 23:27:18, Running: 35:06:49]
[04:34:50] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Ram Usage: 4328 MB / 6372 MB][Ticks: 384]
[04:34:50] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Listen][Mute][Pause][Resume][Stop][Continue][Remove]
[04:47:20] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: 
[04:47:20] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [TaskName: Overworld1][Shape: Square]
[04:47:20] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Dim=Overworld] [Task Type: Fast Check Gen]
[04:47:20] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Task: Current/Total: 207,813/4,428,287]
[04:47:20] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Speed: 2.5 Chunks/t]
[04:47:20] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Loaded (Chunks | Region Files): 272 | 100]
[04:47:20] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Working Area: From[X=5120, Z=11776], To[X=5632, Z=12288]]
[04:47:20] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Time Left: 23:27:21, Running: 35:19:19]
[04:47:20] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Ram Usage: 4692 MB / 6372 MB][Ticks: 99]
[04:47:20] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Listen][Mute][Pause][Resume][Stop][Continue][Remove]
[04:56:52] [Server thread/WARN] [universalmodcore]: Calculating Immersive Railroading Physics Iteration took 23ms (0, 0, 0)
[07:14:00] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: 
[07:14:00] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [TaskName: Overworld1][Shape: Square]
[07:14:00] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Dim=Overworld] [Task Type: Fast Check Gen]
[07:14:00] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Task: Current/Total: 207,814/4,428,287]
[07:14:00] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Speed: 2.5 Chunks/t]
[07:14:00] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Loaded (Chunks | Region Files): 272 | 100]
[07:14:00] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Working Area: From[X=5120, Z=11776], To[X=5632, Z=12288]]
[07:14:00] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Time Left: 23:27:24, Running: 37:45:59]
[07:14:00] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Ram Usage: 4364 MB / 6372 MB][Ticks: 99]
[07:14:00] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: [Listen][Mute][Pause][Resume][Stop][Continue][Remove]
[07:19:10] [User Authenticator #1/INFO] [net.minecraft.server.network.NetHandlerLoginServer]: UUID of player Aintitcrazy is awholebunchofletters
[07:19:10] [Netty Epoll Server IO #2/INFO] [FML]: Client protocol version 2
[07:19:10] [Netty Epoll Server IO #2/INFO] [FML]: Client attempting to join with 31 mods : minecraft@1.12.2,flansmod@5.10.0,buildcraftlib@7.99.24.8,buildcraftsilicon@7.99.24.8,buildcraftenergy@7.99.24.8,buildcrafttransport@7.99.24.8,chunkpregenerator@4.4.0,car@1.2.12,trackapi@1.1,mekanism@1.12.2-9.8.3.390,ic2@2.8.222-ex112,buildcraftbuilders@7.99.24.8,xaerominimap@24.0.1,mcp@9.42,buildcraftfactory@7.99.24.8,galacticraftcore@4.0.6,FML@8.0.99.99,extraplanets@1.12.2-0.7.7,mekanismtools@1.12.2-9.8.3.390,icbmclassic@5.4.0,buildcraftcompat@7.99.24.8,immersiverailroading@1.10.0,xaerominimap_core@1.12.2-1.0,mekanismgenerators@1.12.2-9.8.3.390,galacticraftplanets@4.0.6,micdoodlecore@4.0.6,mjrlegendslib@1.12.2-1.2.1,forge@14.23.5.2859,buildcraftcore@7.99.24.8,buildcraftrobotics@7.99.24.8,universalmodcore@1.2.1
[07:19:12] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
[07:19:12] [Server thread/INFO] [net.minecraft.server.management.PlayerList]: Aintitcrazy[/myinternaliplol:port] logged in with entity id 176417 at (144.39055265380185, 76.68813609806675, 231.01305046804507)
[07:19:12] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Aintitcrazy joined the game
[07:19:12] [Server thread/INFO] [Mekanism]: Sent config to 'Aintitcrazy.'
[07:20:12] [Server Watchdog/FATAL] [net.minecraft.server.dedicated.ServerHangWatchdog]: A single server tick took 60.00 seconds (should be max 0.05)
[07:20:12] [Server Watchdog/FATAL] [net.minecraft.server.dedicated.ServerHangWatchdog]: Considering it to be crashed, server will forcibly shutdown.
[07:20:13] [Server Watchdog/ERROR] [net.minecraft.server.dedicated.ServerHangWatchdog]: This crash report has been saved to: /home/warserver/MC/./crash-reports/crash-2024-04-03_07.20.13-server.txt
[07:20:13] [Server Shutdown Thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
[07:20:13] [Server Shutdown Thread/INFO] [net.minecraft.server.MinecraftServer]: Saving players

</p>
</details>

Updated by Speiger: Added Spoiler on to it so it can be opened/closed

**Comment by Speiger** [comment] 2024-04-03 10:49
@coolboy2002 
I assume you used time per tick 250 or 200 or something in the ballmark.

The problem is: The time per tick maxes the server so much out that your login basically triggers the server watchdog.
That is what causes the crash.

Simply reduce the time per tick or pause/stop the pregenerator before joining.

**Closed as completed by Speiger** 2024-04-03 10:49 UTC
