### ISSUE TITLE
Error on Gen

### ISSUE THREAD

**Issue by UrbanSide** [TinyModularThings/Chunk-Pregenerator-Issue-Tracker#16] opened 2023-01-11 13:55 UTC
**Minecraft 1.18.2**
Lost cities 1.18 5.3.13
Pregen last from curseforge
```
java.lang.ArrayIndexOutOfBoundsException: Index 1492 out of bounds for length 1025
	at it.unimi.dsi.fastutil.longs.LongLinkedOpenHashSet.removeFirstLong(LongLinkedOpenHashSet.java:601) ~[fastutil-8.5.6.jar%2330!/:?] {}
	at net.minecraft.world.level.lighting.DynamicGraphMinFixedPoint.m_75588_(DynamicGraphMinFixedPoint.java:195) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?] {re:classloading}
	at net.minecraft.server.level.DistanceManager$ChunkTicketTracker.m_140877_(DistanceManager.java:511) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?] {re:classloading}
	at net.minecraft.server.level.DistanceManager.m_140805_(DistanceManager.java:118) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:chunkpregen.mixins.json:common.storage.TicketManagerMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerChunkCache.m_8489_(ServerChunkCache.java:283) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:chunkpregen.mixins.json:common.storage.ServerChunkProviderMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_7245_(ServerChunkCache.java:602) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache.m_7587_(ServerChunkCache.java:131) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:chunkpregen.mixins.json:common.storage.ServerChunkProviderMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.m_6522_(Level.java:299) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:sereneseasons.mixins.json:MixinLevel,pl:mixin:APP:lootr.mixins.json:MixinLevel,pl:mixin:A}
	at net.minecraft.world.level.LevelReader.m_46819_(LevelReader.java:123) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?] {re:computing_frames,re:classloading,re:mixin}
	at net.minecraft.world.level.Level.m_6325_(Level.java:294) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:sereneseasons.mixins.json:MixinLevel,pl:mixin:APP:lootr.mixins.json:MixinLevel,pl:mixin:A}
	at net.minecraft.world.level.Level.m_8055_(Level.java:593) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:sereneseasons.mixins.json:MixinLevel,pl:mixin:APP:lootr.mixins.json:MixinLevel,pl:mixin:A}
	at mcjty.lostcities.worldgen.GlobalTodo.lambda$executeAndClearTodo$3(GlobalTodo.java:127) ~[lostcities-1.18-5.3.13.jar%23158!/:1.18-5.3.13] {re:classloading}
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?] {re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin}
	at mcjty.lostcities.worldgen.GlobalTodo.executeAndClearTodo(GlobalTodo.java:124) ~[lostcities-1.18-5.3.13.jar%23158!/:1.18-5.3.13] {re:classloading}
	at mcjty.lostcities.setup.ForgeEventHandlers.onWorldTick(ForgeEventHandlers.java:107) ~[lostcities-1.18-5.3.13.jar%23158!/:1.18-5.3.13] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_1427_ForgeEventHandlers_onWorldTick_WorldTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPostWorldTick(ForgeEventFactory.java:907) ~[forge-1.18.2-40.2.0-universal.jar%23243!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1074) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:chunkpregen.mixins.json:common.server.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:407) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:chunkpregen.mixins.json:common.server.DedicatedServerMixin,pl:mixin:APP:blueprint.mixins.json:DedicatedServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:977) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:chunkpregen.mixins.json:common.server.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:795) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:chunkpregen.mixins.json:common.server.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:253) ~[server-1.18.2-20220404.173914-srg.jar%23238!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:chunkpregen.mixins.json:common.server.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin}
```

**Comment by Speiger** [comment] 2023-01-11 19:51
@UrbanSide is that a constant crash that happens every single time you start a pregeneration?
Or does that happen randomly?
Because this doesn't look like a pregen issue.
@McJty could you provide any input on this one? Since all pregen in 1.18+ does is place chunktickets and remove them the same way "forced chunk command" does?

**Comment by UrbanSide** [comment] 2023-01-11 19:54
@Speiger I start the generation, 2-3 minutes pass, the server crashes with this error.

**Comment by Speiger** [comment] 2023-01-11 20:23
@UrbanSide i will look into it.
Once my Hardware upgrade is done (should be this month) I will start a massive bugfixing patch.
Atm testing isn't really possible because just loading a existing world maxes out my PC to small freezes.
(1.16 or older is fine but 1.18 is just horrible to test with)

**Comment by UrbanSide** [comment] 2023-01-11 20:47
@Speiger Well, thank you very much! If you need a dedicated server, write, I can provide a VPS or host a server for the duration of the tests (of course, for free)

**Comment by Speiger** [comment] 2023-01-11 21:41
@UrbanSide thank you. Already have a few of them. But in this case this can't be tested on a dedicated server, I need to test this on a local machine in a IDE where I can see the data properly of what the problem is ^^

Still thank you.

**Comment by Speiger** [comment] 2023-03-03 16:29
should be fixed.

**Closed by Speiger** 2023-03-03 16:29 UTC
Labels: bug
